/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MappingRouteImport } from './routes/mapping'
import { Route as ProjectsRouteRouteImport } from './routes/projects/route'
import { Route as JobsRouteRouteImport } from './routes/jobs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as ProjectsProjectRouteImport } from './routes/projects/$project'
import { Route as JobsJobidRouteImport } from './routes/jobs/$jobid'
import { Route as footerAboutRouteImport } from './routes/(footer)/about'

const MappingRoute = MappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRouteRoute = JobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRouteRoute,
} as any)
const ProjectsProjectRoute = ProjectsProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const JobsJobidRoute = JobsJobidRouteImport.update({
  id: '/$jobid',
  path: '/$jobid',
  getParentRoute: () => JobsRouteRoute,
} as any)
const footerAboutRoute = footerAboutRouteImport.update({
  id: '/(footer)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/mapping': typeof MappingRoute
  '/about': typeof footerAboutRoute
  '/jobs/$jobid': typeof JobsJobidRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/jobs/': typeof JobsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mapping': typeof MappingRoute
  '/about': typeof footerAboutRoute
  '/jobs/$jobid': typeof JobsJobidRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/jobs': typeof JobsIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/mapping': typeof MappingRoute
  '/(footer)/about': typeof footerAboutRoute
  '/jobs/$jobid': typeof JobsJobidRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/jobs/': typeof JobsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/projects'
    | '/mapping'
    | '/about'
    | '/jobs/$jobid'
    | '/projects/$project'
    | '/jobs/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mapping'
    | '/about'
    | '/jobs/$jobid'
    | '/projects/$project'
    | '/jobs'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/jobs'
    | '/projects'
    | '/mapping'
    | '/(footer)/about'
    | '/jobs/$jobid'
    | '/projects/$project'
    | '/jobs/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRouteRoute: typeof JobsRouteRouteWithChildren
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  MappingRoute: typeof MappingRoute
  footerAboutRoute: typeof footerAboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mapping': {
      id: '/mapping'
      path: '/mapping'
      fullPath: '/mapping'
      preLoaderRoute: typeof MappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRouteRoute
    }
    '/projects/$project': {
      id: '/projects/$project'
      path: '/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof ProjectsProjectRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/jobs/$jobid': {
      id: '/jobs/$jobid'
      path: '/$jobid'
      fullPath: '/jobs/$jobid'
      preLoaderRoute: typeof JobsJobidRouteImport
      parentRoute: typeof JobsRouteRoute
    }
    '/(footer)/about': {
      id: '/(footer)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof footerAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JobsRouteRouteChildren {
  JobsJobidRoute: typeof JobsJobidRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteRouteChildren: JobsRouteRouteChildren = {
  JobsJobidRoute: JobsJobidRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteRouteWithChildren = JobsRouteRoute._addFileChildren(
  JobsRouteRouteChildren,
)

interface ProjectsRouteRouteChildren {
  ProjectsProjectRoute: typeof ProjectsProjectRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsProjectRoute: ProjectsProjectRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRouteRoute: JobsRouteRouteWithChildren,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  MappingRoute: MappingRoute,
  footerAboutRoute: footerAboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
